---
- debug: msg="Originating connection from {{ he4to6_local_addr }}"
- name: Create interface configuration
  template:
    src="interface.j2"
    dest="/etc/network/interfaces.d/{{ he4to6__iface_name }}.cfg"

- name: Bring up new interface
  shell: (timeout 10 ifdown {{ he4to6__iface_name }}; timeout 10 ifup {{ he4to6__iface_name }}) ; /bin/true

# vim: ft=ansible
